### ISSUE TITLE
several php.ini

### ISSUE THREAD

**Issue by VoidAndAny** [jolicode/chef-cookbook-php#1]
Thanks for this cookbook, for me it's more accurate than the official one.

I've got a question is it possible to have multiple location for php.ini (ie. /etc/php5/apache2 and /etc/php5/cli) ?

And maybe several php.ini (different config) for the differents locations ?

**Comment by joelwurtz** [comment]
Certainly,

Look at the ext-fpm recipe i drop php.ini in a different directory to not have the same configuration for cli and fpm, if you use apache you can certainly add a template ressource which use the php.ini.erb template of this cookbook.

The only thing which need to be fix is copying default attributes for all this different location, i have no found for the moment (i'm no use to ruby :( ) how to properly clone a set of attributes : if you look a fpm.rb attribute file config is the same as in config.rb file (and it will be easier to maintain one attribute file with default config)
