### ISSUE TITLE
Directory is not empty in :create_project action

### ISSUE THREAD

**Issue by dyjo** [jolicode/chef-cookbook-php#2]
Composer throws an error when you try to create a project in a directory that is not empty. So if your chef run includes the :create_project action, it will fail for any run but the first unless you add a conditional to check whether or not the directory is empty.

I think that conditional logic should be contained in the :create_project action and throw a warning that the action was not executed instead of failing the entire chef run.

**Comment by joelwurtz** [comment]
This should be better now

**Comment by dyjo** [comment]
Looks good, thanks a bunch!
