### ISSUE TITLE
Create fpm pools

### ISSUE THREAD

**Issue by jstoeffler** [jolicode/chef-cookbook-php#4]
Hi,

I'm willing to use your cookbook instead of the official one.
I don't get if it's possible to create fpm pools like in the official cookbook.

You create a default pool, but it's not likely to be what will be needed : 

In recipes/ext-fpm.rb : 

```
# default pool
php_fpm_pool "www" do
  action :run
end
```

In definitions/php_fpm_pools.rb :

```
define :php_fpm_pool, :cookbook => "jolicode-php", :user => "www-data", :group => "www-data" do

  if !params[:listen]
    params[:listen] = "/var/run/php5-fpm-#{params[:name]}.sock"
  end

  var = params

  config = {
    'name'   => params[:name],
    'user'   => params[:user],
    'group'  => params[:group],
    'listen' => params[:listen]
  }

  template "#{node['jolicode-php']['fpm_pool_dir']}/#{var[:name]}.conf" do
    source "fpm-pool.conf.erb"
    owner "root"
    group "root"
    cookbook  var[:cookbook]
    mode "0644"
    variables({
      :config => config
    })
  end
end
```

It seems that you have parameters like "listen" which I'd like to change. Can this be done with the current plugin ? Or would you accept a pull request for that ?

**Comment by ghost** [comment]
[priestjim](http://github.com/priestjim/chef-php) has done some work on this already, as a fork from the opscode php cookbook. I think it would be worth wile to look at the lwrp he has created, as a possible starting point.

[resource](https://github.com/priestjim/chef-php/blob/master/resources/fpm.rb)
[provider](https://github.com/priestjim/chef-php/blob/master/providers/fpm.rb)

**Comment by joelwurtz** [comment]
Hi,

WIth the current version you can specify a listen param to the definition : 

```
php_fpm_pool "mypool" do
  action :run
  listen "/var/run/mypool.sock"
end
```

But due to #5  this will change with a replacment of definition by a LWRP, so it will be 

```
jolicode_php_fpm_pool "mypool" do
  user "mypool_user"
  group "mypool_group"
  listen "/var/run/mypool.sock"
  notifies :restart, "service[php-fpm]"
end
```

in the new version
