### ISSUE TITLE
[Feature] Recipes for popular frameworks

### ISSUE THREAD

**Issue by dyjo** [jolicode/chef-cookbook-php#8]
It might be nice to have recipes for the popular frameworks out there. So when you've helped a client make a decision on using Drupal, Wordpress, Symfony, Laravel, etc. you've only got to run a single command to get the development environment going.

**Comment by joelwurtz** [comment]
Yes it will be nice but in another cookbook which can depend on this one or the official one.

Too many features is not good for a cookbook, i just want to restrict this cookbook to php and his extension / tool not the framework.
